// Radial color change -- Generated by ChatGPT
const body = document.body;

let color1 = randomHSL();
let color2 = randomHSL();

function randomHSL() {
    const h = Math.floor(Math.random() * 360);
    const s = 70 + Math.random() * 30;
    const l = 50 + Math.random() * 10;
    return {h, s, l};
}

function hslString(c) {
    return `hsl(${c.h}, ${c.s}%, ${c.l}%)`;
}

function animate() {
    // Slowly shift hues
    color1.h = (color1.h + 0.2) % 360;
    color2.h = (color2.h + 0.15) % 360;

    // Apply radial gradient
    body.style.background = `radial-gradient(circle, ${hslString(color1)} 0%, ${hslString(color2)} 100%)`;

    requestAnimationFrame(animate);
}
animate();


// Vertical to horizontal scroll
const scrollContainer = document.getElementById('scroll-container');

scrollContainer.addEventListener('wheel', (evt) => {
    evt.preventDefault(); // prevent vertical scrolling
    scrollContainer.scrollLeft += evt.deltaY; // move horizontal by vertical delta
});
